# Generated by Django 5.1.4 on 2026-07-16 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("regex", models.CharField(blank=True, max_length=255)),
                ("stop_processing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="#1f4e78", max_length=9)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("rule", "Rule"), ("ai", "AI")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="uniq_owner_folder",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="transactions",
        ),
        migrations.AddField(
            model_name="folder",
            name="criteria",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="folder",
            name="excluded_transactions",
            field=models.ManyToManyField(
                blank=True, related_name="excluded_from_folders", to="core.transaction"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="included_transactions",
            field=models.ManyToManyField(
                blank=True, related_name="included_in_folders", to="core.transaction"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="tag_match",
            field=models.CharField(
                choices=[("any", "Any"), ("all", "All")], default="any", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="counterparty",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rule",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="rules", to="core.tag"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="folders", to="core.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                fields=("owner", "parent", "name"), name="uniq_owner_parent_folder"
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="core.rule",
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_links",
                to="core.tag",
            ),
        ),
        migrations.AddField(
            model_name="transactiontag",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_links",
                to="core.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                through="core.TransactionTag",
                to="core.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="uniq_owner_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"), name="uniq_transaction_tag"
            ),
        ),
    ]
