# Generated by Django 5.1.4 on 2026-08-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="bic",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="correspondent_bic",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="is_invoice_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                (
                    "vat_mode",
                    models.CharField(
                        choices=[
                            ("reverse_charge", "Reverse charge (NP)"),
                            ("standard", "Standard VAT"),
                            ("exempt", "Exempt (ZW)"),
                        ],
                        default="reverse_charge",
                        max_length=20,
                    ),
                ),
                (
                    "default_vat_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("default_description", models.CharField(blank=True, max_length=255)),
                (
                    "default_unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="EUR", max_length=8)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("issued", "Issued")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=40)),
                ("service_year", models.PositiveIntegerField()),
                ("service_month", models.PositiveSmallIntegerField()),
                ("issue_date", models.DateField()),
                ("sale_date", models.DateField()),
                ("due_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "vat_label",
                    models.CharField(blank=True, default="NP", max_length=20),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("issuer_name", models.CharField(blank=True, max_length=200)),
                ("issuer_trade_name", models.CharField(blank=True, max_length=200)),
                ("issuer_vat_number", models.CharField(blank=True, max_length=40)),
                ("issuer_address", models.TextField(blank=True)),
                ("issuer_city", models.CharField(blank=True, max_length=120)),
                ("issuer_country", models.CharField(blank=True, max_length=120)),
                ("issuer_phone", models.CharField(blank=True, max_length=40)),
                ("issuer_email", models.EmailField(blank=True, max_length=254)),
                ("issuer_legal_form", models.CharField(blank=True, max_length=120)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("client_tax_id", models.CharField(blank=True, max_length=40)),
                ("client_address", models.TextField(blank=True)),
                ("vat_mode", models.CharField(blank=True, max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("bic", models.CharField(blank=True, max_length=20)),
                ("correspondent_bic", models.CharField(blank=True, max_length=20)),
                ("bank_address", models.CharField(blank=True, max_length=255)),
                ("xlsx_file", models.FileField(blank=True, upload_to="invoices/")),
                ("pdf_file", models.FileField(blank=True, upload_to="invoices/")),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="core.account",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.client",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IssuerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("vat_number", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "country",
                    models.CharField(blank=True, default="Spain", max_length=120),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        default="Private Entrepreneur | Autónomo",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="uniq_owner_client"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["owner", "service_year", "service_month"],
                name="core_invoic_owner_i_fc5cfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["owner", "status"], name="core_invoic_owner_i_0fd60b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="uniq_owner_invoice_number"
            ),
        ),
    ]
