# Generated by Django 5.1.4 on 2026-08-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invoicing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("agreement", "Agreement"),
                            ("order", "Order"),
                            ("offer", "Offer"),
                            ("tax_declaration", "Tax declaration"),
                            ("tax_certificate", "Tax certificate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for personal documents (tax, certificates, etc.).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.client",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "kind"], name="core_docume_owner_i_53aeef_idx"
                    ),
                    models.Index(
                        fields=["owner", "client"],
                        name="core_docume_owner_i_bb22df_idx",
                    ),
                ],
            },
        ),
    ]
