# Generated by Django 5.1.4

from django.db import migrations, models


def backfill_balances(apps, schema_editor):
    Account = apps.get_model("core", "Account")
    Transaction = apps.get_model("core", "Transaction")
    for account in Account.objects.all():
        last = (
            Transaction.objects.filter(account=account, balance__isnull=False)
            .order_by("-operation_date", "-id")
            .first()
        )
        if last is None:
            continue
        account.balance = last.balance
        account.save(update_fields=["balance"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[("bank", "Bank"), ("cash", "Cash"), ("debt", "Debt")],
                default="bank",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["kind", "group", "name"]},
        ),
        migrations.RunPython(backfill_balances, noop),
    ]
