# Generated by Django 5.1.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_account_kind_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                            ("quarter", "Quarterly"),
                            ("year", "Yearly"),
                        ],
                        default="month",
                        max_length=8,
                    ),
                ),
                (
                    "due_day",
                    models.SmallIntegerField(
                        default=1,
                        help_text="Weekday 0–6 (Mon–Sun) for weekly; day of month 1–31 otherwise.",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("match_text", models.CharField(blank=True, max_length=255)),
                (
                    "amount_tolerance_pct",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                ("auto_match", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tax", "Tax"),
                            ("loan", "Loan"),
                            ("subscription", "Subscription"),
                            ("income", "Income"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurrences",
                        to="core.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="recurrences", to="core.tag"
                    ),
                ),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="core.recurrence",
            ),
        ),
    ]
