# Generated by Django 5.1.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_recurrence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "irpf_method",
                    models.CharField(
                        choices=[("modelo_130", "Modelo 130")],
                        default="modelo_130",
                        max_length=16,
                    ),
                ),
                (
                    "withholding_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("simplificada", models.BooleanField(default=True)),
                (
                    "income_from",
                    models.CharField(
                        choices=[
                            ("invoices", "Issued invoices"),
                            ("tags", "Tagged bank income"),
                        ],
                        default="invoices",
                        max_length=12,
                    ),
                ),
                (
                    "ss_mode",
                    models.CharField(
                        choices=[("table", "RETA tramos"), ("fixed", "Fixed cuota")],
                        default="table",
                        max_length=8,
                    ),
                ),
                (
                    "ss_cuota_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("new_autonomo_start", models.DateField(blank=True, null=True)),
                (
                    "planned_income_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deductible_tags",
                    models.ManyToManyField(
                        blank=True, related_name="tax_profiles", to="core.tag"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
