# Generated by Django 5.1.4 on 2026-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_taxprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiontag",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("rule", "Rule"),
                    ("ai", "AI"),
                    ("schedule", "Schedule"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
