# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_transactiontag_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="If set, stored balance is available credit; real = balance − limit.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
